### ISSUE TITLE
bug: missing best approximation

### ISSUE THREAD

**Issue by TallKite** [m-yac/microtonal-utils#1]
enter 400c, for 13-limit and 81-odd-limit and Tenney-height-sorting it shows 5/4 and 81/64 
should get 63/50 without having to search for more, since it has a lower Tenney height than 81/64

Also for 1/2xP8 -  7/5 and 10/7 should come first

**Comment by m-yac** [comment]
I have since clarified that the default sort is not actually sorting by Tenney height – it's by what I'm calling "no-2s Tenney height", where you remove all factors of 2 before computing the height. (For some reason I thought removing factors of 2 wouldn't change the order? No idea why...)

The reason I'm keeping this the default sort despite finding out that it's not actually Tenney height is because I find it often gives better (or maybe, "more familiar"?) results than actually sorting by Tenney height. For example, the results for [M3\12](https://www.yacavone.net/xen-calc/?q=M3%5C12) and [m3\12](https://www.yacavone.net/xen-calc/?q=m3%5C12) are exactly the corresponding 5-limit and 3-limit thirds when sorting by no-2s Tenney height. I've also added the option to actually sort by Tenney height, so you can compare the results if you want.

I'm leaving this issue open because I'm curious if "no-2s Tenney height" is too weird or too non-standard to have as a default. I'm happy to remove it from the default spot or even remove it all together if there's some conceptual reason to do so.
