### ISSUE TITLE
bug: "-a" delimiter not parsed correctly

### ISSUE THREAD

**Issue by TallKite** [m-yac/microtonal-utils#2]
entered "triloru-agu4", which is [1 0 -1 -3 3>, got an error
perhaps the code confuses a hyphen with a minus sign?

**Comment by m-yac** [comment]
Fixed in 99a129484427f09314bdee767a78d9e667daba6c. Thanks for catching this!

This post also made me realize that monzos are not usually written with commas, so I added the ability to parse monzos without commas in b551a59547e31d3a3d1cc71ba3ba7ad719921fe2 – e.g. https://www.yacavone.net/xen-calc/?q=[-2+0+1>
